title: Below
email: below@innusource.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://innusource.xyz/below" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]


# Build settings
sass:
  sass_dir: _sass
  style: :compressed

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
    auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-toc

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.MD
  - .gitignore

toc:
  min_level: 2
  max_level: 4
