title: Below
email: contact@innusource.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://below.innusource.xyz/"
twitter_username: jekyllrb
github_username:  jekyll

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]


# Build settings
sass:
  sass_dir: _sass
  style: :compressed

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
    auto_ids: true

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.md
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json
  - dist
  - CNAME
