languageCode: "en"
title: "Below"
baseURL: "https://below.hyphev.com"
enableInlineShortcodes: true

pygmentsUseClasses: true
# you can use ```lang if you want too
pygmentsCodeFences: true

buildDrafts: true
buildFuture: true

enableRobotsTXT: true
metaDataFormat: "yaml"
disableKinds: ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions: false

publishDir: "_site"
archetypeDir: "site/archetypes"
assetDir: "site/assets"
contentDir: "site/content"
dataDir: "site/data"
layoutDir: "site/layouts"
staticDir: "site/static"
themesDir: "site/themes"

params:
  description: "The CSS design system of hyphev projects."
  authors: "Below contributors"
  docs_version: 0.0.1